name: Deploy Bunny Scripting Script

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  update-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Publish the script to Bunny
        uses: "BunnyWay/actions/deploy-script@main"
        with:
          script_id: 60112
          file: "script.ts"
          deploy_key: ${{ secrets.BUNNY_API_KEY }}